markdown: rdiscount
permalink: /:title/
url: touzi.github.io
name: 头子
author: 头子
qq: 305749023
email: policetouzi@163.com
duoshuo: policetouzi
beian: 京ICP备12345678号
cnzz: 1000428426
weibo: 1622178027
github: touzi
pygments: true
safe: true
paginate: 20
about: "这里是 touzi 的个人博客，创建于 2014 年。2014年5月迁移到 Jekyll @ GitHub。<br /><br />职业coder，纯北漂，蜗居北京西城.这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
